-- ============================================================================
-- Red Talento TP — schema DDL for production (Supabase)
--
-- Generated by hand from the TypeORM entities under backend/src/**/*.entity.ts,
-- for environments where `synchronize: true` is disabled (NODE_ENV=production).
-- Run this once against the Supabase Postgres database before deploying.
--
-- Notes:
--  - Column/table names are double-quoted to preserve the exact camelCase
--    TypeORM uses at runtime (Postgres would otherwise lowercase them).
--  - Constraint/FK names here are descriptive, not TypeORM's internal hashed
--    names — cosmetic difference only, does not affect app behaviour.
--  - `comments`, `publication_likes`, `skills.validatedBy` and
--    `skill_endorsements.userId` reference other tables by id but have NO
--    relation decorator in the entity, so TypeORM never creates a real FK or
--    uuid type for them — they are plain varchar columns here too, to match.
--  - Safe to re-run: tables use IF NOT EXISTS, enum types are guarded.
-- ============================================================================

-- ── Enum types ───────────────────────────────────────────────────────────────
DO $$ BEGIN
  CREATE TYPE "users_role_enum" AS ENUM ('STUDENT', 'EMPRESA', 'COLEGIO');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "skills_category_enum" AS ENUM ('TECNICA', 'BLANDA', 'CERTIFICACION');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "skills_validationStatus_enum" AS ENUM ('PENDIENTE', 'VALIDADA', 'RECHAZADA');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "portfolio_evidences_type_enum" AS ENUM ('PROYECTO', 'CERTIFICADO', 'FOTO', 'DESCRIPCION', 'VIDEO');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "opportunities_type_enum" AS ENUM ('PASANTIA', 'PRACTICA', 'TRABAJO', 'PROYECTO');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "applications_status_enum" AS ENUM ('PENDIENTE', 'EN_REVISION', 'ENTREVISTA', 'ACEPTADO', 'RECHAZADO');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "notifications_type_enum" AS ENUM (
    'SKILL_VALIDATED', 'SKILL_REJECTED', 'APPLICATION_STATUS', 'NEW_MESSAGE',
    'LIKE', 'COMMENT', 'FOLLOW_REQUEST', 'FOLLOW_ACCEPTED', 'NEW_FOLLOWER', 'GENERAL'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "follows_status_enum" AS ENUM ('PENDING', 'ACCEPTED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── users ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "users" (
  "id"        uuid NOT NULL DEFAULT gen_random_uuid(),
  "email"     character varying(255) NOT NULL,
  "password"  character varying(255) NOT NULL,
  "role"      "users_role_enum" NOT NULL,
  "isActive"  boolean NOT NULL DEFAULT true,
  "avatar"    character varying,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT "PK_users" PRIMARY KEY ("id"),
  CONSTRAINT "UQ_users_email" UNIQUE ("email")
);

-- ── student_profiles ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "student_profiles" (
  "id"               uuid NOT NULL DEFAULT gen_random_uuid(),
  "userId"           uuid NOT NULL,
  "firstName"        character varying(100) NOT NULL,
  "lastName"         character varying(100) NOT NULL,
  "headline"         character varying(255),
  "bio"              text,
  "specialty"        character varying(150) NOT NULL,
  "year"             integer NOT NULL DEFAULT 1,
  "gpa"              numeric(3,1),
  "phone"            character varying,
  "location"         character varying,
  "avatar"           character varying,
  "coverImage"       character varying,
  "linkedinUrl"      character varying,
  "githubUrl"        character varying,
  "portfolioUrl"     character varying,
  "schoolUserId"     character varying,
  "readinessScore"   integer NOT NULL DEFAULT 0,
  "profileViews"     integer NOT NULL DEFAULT 0,
  "createdAt"        TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt"        TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT "PK_student_profiles" PRIMARY KEY ("id"),
  CONSTRAINT "UQ_student_profiles_userId" UNIQUE ("userId"),
  CONSTRAINT "FK_student_profiles_userId" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE
);

-- ── company_profiles ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "company_profiles" (
  "id"          uuid NOT NULL DEFAULT gen_random_uuid(),
  "userId"      uuid NOT NULL,
  "name"        character varying(200) NOT NULL,
  "description" text,
  "industry"    character varying(100),
  "size"        character varying(100),
  "location"    character varying,
  "website"     character varying,
  "logo"        character varying,
  "coverImage"  character varying,
  "createdAt"   TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt"   TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT "PK_company_profiles" PRIMARY KEY ("id"),
  CONSTRAINT "UQ_company_profiles_userId" UNIQUE ("userId"),
  CONSTRAINT "FK_company_profiles_userId" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE
);

-- ── school_profiles ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "school_profiles" (
  "id"           uuid NOT NULL DEFAULT gen_random_uuid(),
  "userId"       uuid NOT NULL,
  "name"         character varying(200) NOT NULL,
  "description"  text,
  "location"     character varying,
  "website"      character varying,
  "logo"         character varying,
  "coverImage"   character varying,
  "specialties"  text,
  "createdAt"    TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt"    TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT "PK_school_profiles" PRIMARY KEY ("id"),
  CONSTRAINT "UQ_school_profiles_userId" UNIQUE ("userId"),
  CONSTRAINT "FK_school_profiles_userId" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE
);

-- ── skills ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "skills" (
  "id"                uuid NOT NULL DEFAULT gen_random_uuid(),
  "studentId"         uuid NOT NULL,
  "name"              character varying(100) NOT NULL,
  "category"          "skills_category_enum" NOT NULL,
  "level"             integer,
  "isValidated"       boolean NOT NULL DEFAULT false,
  "validationStatus"  "skills_validationStatus_enum" NOT NULL DEFAULT 'PENDIENTE',
  "validatedBy"       character varying,
  "validatedAt"       TIMESTAMP,
  "validationNotes"   character varying,
  "endorsements"      integer NOT NULL DEFAULT 0,
  "createdAt"         TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt"         TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT "PK_skills" PRIMARY KEY ("id"),
  CONSTRAINT "FK_skills_studentId" FOREIGN KEY ("studentId") REFERENCES "student_profiles" ("id") ON DELETE CASCADE
);

-- ── skill_endorsements ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "skill_endorsements" (
  "id"        uuid NOT NULL DEFAULT gen_random_uuid(),
  "skillId"   uuid NOT NULL,
  "userId"    character varying NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT "PK_skill_endorsements" PRIMARY KEY ("id"),
  CONSTRAINT "UQ_skill_endorsements_skillId_userId" UNIQUE ("skillId", "userId"),
  CONSTRAINT "FK_skill_endorsements_skillId" FOREIGN KEY ("skillId") REFERENCES "skills" ("id") ON DELETE CASCADE
);

-- ── portfolio_evidences ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "portfolio_evidences" (
  "id"          uuid NOT NULL DEFAULT gen_random_uuid(),
  "studentId"   uuid NOT NULL,
  "title"       character varying(200) NOT NULL,
  "description" text,
  "type"        "portfolio_evidences_type_enum" NOT NULL DEFAULT 'PROYECTO',
  "url"         character varying,
  "imageUrl"    character varying,
  "tags"        text,
  "isPublic"    boolean NOT NULL DEFAULT true,
  "createdAt"   TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt"   TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT "PK_portfolio_evidences" PRIMARY KEY ("id"),
  CONSTRAINT "FK_portfolio_evidences_studentId" FOREIGN KEY ("studentId") REFERENCES "student_profiles" ("id") ON DELETE CASCADE
);

-- ── opportunities ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "opportunities" (
  "id"               uuid NOT NULL DEFAULT gen_random_uuid(),
  "companyId"        uuid NOT NULL,
  "title"            character varying(200) NOT NULL,
  "description"      text NOT NULL,
  "type"             "opportunities_type_enum" NOT NULL,
  "location"         character varying(150) NOT NULL,
  "isRemote"         boolean NOT NULL DEFAULT false,
  "salary"           character varying,
  "requirements"     text,
  "skills"           text,
  "specialty"        character varying,
  "startDate"        date,
  "endDate"          date,
  "deadline"         date,
  "isActive"         boolean NOT NULL DEFAULT true,
  "applicantsCount"  integer NOT NULL DEFAULT 0,
  "savedBy"          text,
  "createdAt"        TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt"        TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT "PK_opportunities" PRIMARY KEY ("id"),
  CONSTRAINT "FK_opportunities_companyId" FOREIGN KEY ("companyId") REFERENCES "company_profiles" ("id") ON DELETE CASCADE
);

-- ── applications ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "applications" (
  "id"                 uuid NOT NULL DEFAULT gen_random_uuid(),
  "studentId"          uuid NOT NULL,
  "opportunityId"      uuid NOT NULL,
  "status"             "applications_status_enum" NOT NULL DEFAULT 'PENDIENTE',
  "coverLetter"        text,
  "notes"              text,
  "hiddenFromProfile"  boolean NOT NULL DEFAULT false,
  "createdAt"          TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt"          TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT "PK_applications" PRIMARY KEY ("id"),
  CONSTRAINT "FK_applications_studentId" FOREIGN KEY ("studentId") REFERENCES "student_profiles" ("id") ON DELETE CASCADE,
  CONSTRAINT "FK_applications_opportunityId" FOREIGN KEY ("opportunityId") REFERENCES "opportunities" ("id") ON DELETE CASCADE
);

-- ── messages ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "messages" (
  "id"         uuid NOT NULL DEFAULT gen_random_uuid(),
  "senderId"   uuid NOT NULL,
  "receiverId" uuid NOT NULL,
  "content"    text NOT NULL,
  "isRead"     boolean NOT NULL DEFAULT false,
  "createdAt"  TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT "PK_messages" PRIMARY KEY ("id"),
  CONSTRAINT "FK_messages_senderId" FOREIGN KEY ("senderId") REFERENCES "users" ("id") ON DELETE CASCADE,
  CONSTRAINT "FK_messages_receiverId" FOREIGN KEY ("receiverId") REFERENCES "users" ("id") ON DELETE CASCADE
);

-- ── publications ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "publications" (
  "id"             uuid NOT NULL DEFAULT gen_random_uuid(),
  "authorId"       uuid NOT NULL,
  "authorType"     character varying,
  "authorName"     character varying,
  "content"        text NOT NULL,
  "imageUrl"       character varying,
  "isStory"        boolean NOT NULL DEFAULT false,
  "storyDuration"  integer,
  "likes"          integer NOT NULL DEFAULT 0,
  "comments"       integer NOT NULL DEFAULT 0,
  "views"          integer NOT NULL DEFAULT 0,
  "tags"           text,
  "isPinned"       boolean NOT NULL DEFAULT false,
  "createdAt"      TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt"      TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT "PK_publications" PRIMARY KEY ("id"),
  CONSTRAINT "FK_publications_authorId" FOREIGN KEY ("authorId") REFERENCES "users" ("id") ON DELETE CASCADE
);

-- ── comments (no relation decorators in entity ⇒ no FK, plain varchar ids) ────
CREATE TABLE IF NOT EXISTS "comments" (
  "id"             uuid NOT NULL DEFAULT gen_random_uuid(),
  "publicationId"  character varying NOT NULL,
  "authorId"       character varying NOT NULL,
  "authorName"     character varying,
  "content"        text NOT NULL,
  "createdAt"      TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT "PK_comments" PRIMARY KEY ("id")
);

-- ── publication_likes (composite PK, no relation decorators ⇒ no FK) ─────────
CREATE TABLE IF NOT EXISTS "publication_likes" (
  "userId"         character varying NOT NULL,
  "publicationId"  character varying NOT NULL,
  "createdAt"      TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT "PK_publication_likes" PRIMARY KEY ("userId", "publicationId")
);

-- ── notifications ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "notifications" (
  "id"        uuid NOT NULL DEFAULT gen_random_uuid(),
  "userId"    uuid NOT NULL,
  "type"      "notifications_type_enum" NOT NULL DEFAULT 'GENERAL',
  "title"     character varying(200) NOT NULL,
  "body"      text NOT NULL,
  "isRead"    boolean NOT NULL DEFAULT false,
  "link"      character varying,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT "PK_notifications" PRIMARY KEY ("id"),
  CONSTRAINT "FK_notifications_userId" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE
);

-- ── follows ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "follows" (
  "id"          uuid NOT NULL DEFAULT gen_random_uuid(),
  "followerId"  uuid NOT NULL,
  "followeeId"  uuid NOT NULL,
  "status"      "follows_status_enum" NOT NULL DEFAULT 'ACCEPTED',
  "createdAt"   TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT "PK_follows" PRIMARY KEY ("id"),
  CONSTRAINT "UQ_follows_followerId_followeeId" UNIQUE ("followerId", "followeeId"),
  CONSTRAINT "FK_follows_followerId" FOREIGN KEY ("followerId") REFERENCES "users" ("id") ON DELETE CASCADE,
  CONSTRAINT "FK_follows_followeeId" FOREIGN KEY ("followeeId") REFERENCES "users" ("id") ON DELETE CASCADE
);
